---
- name: Set hosts
  hosts:
    - http
    - tor
    - i2p
  tasks:
    - include_vars: .vars/hosts.yml

    - name: Write https host
      become: yes
      command: docker exec -it privnote-redis redis-cli -n 3 set HTTPS {{ hosts.https }}

    - name: Write tor host
      become: yes
      command: docker exec -it privnote-redis redis-cli -n 3 set TOR {{ hosts.tor }}

    - name: Write i2p host
      become: yes
      command: docker exec -it privnote-redis redis-cli -n 3 set I2P {{ hosts.i2p }}
