---
- name: Run TOR instance
  hosts: tor
  tasks:
    - name: Copy backend
      become: yes
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/backend/privnote"
        dest: /var/opt
        owner: root
        group: root
        mode: '0644'

    - name: Create docker network
      become: yes
      docker_network:
        name: privbird
        ipam_config:
          - subnet: 172.30.0.0/24
            gateway: 172.30.0.1

    - name: Run docker-compose.yml
      become: yes
      docker_compose:
        project_src: "/var/opt/privnote/"
      environment:
        CELERY_DEFAULT_QUEUE: TOR
        RABBITMQ_HOST: "{{ hostvars['common'].ansible_host }}"

    - name: Copy frontend
      become: yes
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/frontend"
        dest: /var/opt
        owner: root
        group: root
        mode: '0644'

    - name: Run TOR-fe docker-compose.yml
      become: yes
      docker_compose:
        project_src: "/var/opt/frontend/"
      environment:
        FEEDBACK_URL: "http://{{ hostvars['common'].ansible_host }}:8000"

    - name: Get TOR instance onion address
      become: yes
      command: sudo docker exec -it tor onions --json
      register: tor_onion_addr
