# Generated by Django 4.0 on 2022-10-14 17:05

from django.db import migrations, models
import django.db.models.deletion

import secnote.models


class Migration(migrations.Migration):
    initial = True
    
    dependencies = []
    
    operations = [
        migrations.CreateModel(
            name = 'Notification',
            fields = [
                ('id', models.AutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
                ('main', models.BooleanField(default = False)),
                ('fake', models.BooleanField(default = False)),
                ('email', models.EmailField(blank = True, max_length = 254, null = True)),
            ],
        ),
        migrations.CreateModel(
            name = 'FakeNote',
            fields = [
                ('id', models.AutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
                ('content', models.TextField(blank = True)),
                ('password', models.CharField(blank = True, max_length = 100, null = True)),
                ('salt', models.CharField(blank = True, max_length = 32)),
            ],
        ),
        migrations.CreateModel(
            name = 'Option',
            fields = [
                ('id', models.AutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
                ('type', models.CharField(choices = [('HTTPS', 'HTTPS'), ('ONION', 'ONION'), ('I2P', 'I2P')], default = 'HTTPS', max_length = 5)),
                ('auto_destruction', models.CharField(choices = [('AFTER_DAY', 'AFTER_DAY'), ('AFTER_WEEK', 'AFTER_WEEK'), ('AFTER_MONTH', 'AFTER_MONTH'), ('DEFAULT', 'DEFAULT')], default = 'DEFAULT', max_length = 11)),
                ('expiration_time', models.DateTimeField(blank = True, null = True)),
                ('password', models.CharField(blank = True, max_length = 100, null = True)),
                ('salt', models.CharField(blank = True, max_length = 32)),
                ('confirmation', models.IntegerField(default = 0)),
                ('notification', models.ForeignKey(null = True, on_delete = django.db.models.deletion.SET_NULL, to = 'secnote.notification')),
                ('fake_note', models.ForeignKey(null = True, on_delete = django.db.models.deletion.SET_NULL, to = 'secnote.fakenote')),
                ('falsification', models.BooleanField(default = True)),
            ],
        ),
        migrations.CreateModel(
            name = 'Note',
            fields = [
                ('id', models.AutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
                ('slug', models.SlugField(default = secnote.models.generate_slug, unique = True)),
                ('content', models.TextField()),
                ('option', models.ForeignKey(null = True, on_delete = django.db.models.deletion.SET_NULL, to = 'secnote.option')),
            ],
        ),
        migrations.CreateModel(
            name = 'Support',
            fields = [
                ('id', models.AutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
                ('problem', models.TextField()),
                ('email', models.EmailField(blank = True, max_length = 254, null = True)),
            ],
        ),
    ]