version: "3.5"

services:
  tor:
    image: goldy/tor-hidden-service:latest
    container_name: tor
    links:
      - nginx
    environment:
      PB_TOR_SERVICE_HOSTS: '80:nginx:80'

  nginx:
    build:
      context: .
      args:
        mode: dev
    ports:
      - "80:80"
    volumes:
      - ./nginx/log/:/var/log/nginx/
      - ./dist/:/frontend/
    env_file:
      - .env.prod
    environment:
      FEEDBACK_URL: http://192.168.173.110:8000

networks:
  default:
    name: privbird
    external: true
