version: "3.5"

services:
  nginx:
    build:
      context: .
      args:
        mode: prod
    ports:
      - "80:80"
    volumes:
      - ./nginx/log/:/var/log/nginx/
      - ./dist/:/frontend/
    environment:
      FEEDBACK_URL: ${FEEDBACK_URL}
    env_file:
      - .env.prod

networks:
  default:
    name: privbird
    external: true
