version: "3"

services:
  nginx:
    build:
      context: .
      args:
        mode: dev
    ports:
      - "80:80"
    volumes:
      - ./nginx/log/:/var/log/nginx/
      - ./dist/:/frontend/
    env_file:
        - .env.prod
