version: '3'

services:
  backend:
    build: ./backend/
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
    env_file:
      - .env.dev
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: db
    hostname: db
    image: mariadb
    restart: always
    env_file:
      - .env.dev

  redis:
    image: redis:6-alpine

  frontend:
    build: ./frontend/
    ports:
      - "8002:80"
    volumes:
      - .:/app
    links:
      - backend:backend

volumes:
  mysql_data: