version: '3'

services:
  backend:
    build: ./backend/
    command: gunicorn -c ./backend/gunicorn.conf.py privbird.wsgi
    expose:
      - "8000"
    env_file:
      - .env.prod
    environment:
      DB_HOST: db
    volumes:
      - .:/app
    depends_on:
      - db

  celery:
    build: ./backend/
    command: celery -A privbird worker -B -l INFO
    env_file:
        - .env.dev
    environment:
      DB_HOST: db
      CELERY_BROKER_URL: redis://redis:6379/0
    volumes:
        - .:/app
    depends_on:
        - backend
        - redis

  db:
    container_name: db
    hostname: db
    image: mariadb
    restart: always
    env_file:
      - .env.prod
    volumes:
      - mysql_data:/var/lib/mysql/data/

  redis:
    hostname: redis
    image: redis:6-alpine

  frontend:
    build: ./frontend/
    ports:
      - "8002:80"
    volumes:
      - .:/app
    links:
      - backend:backend

volumes:
  mysql_data: