version: '3'

services:
  backend:
    build: ./backend/
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env.dev
    environment:
      DB_HOST: mariadb
      CELERY_BROKER_URL: redis://redis:6379/0
    volumes:
      - ./backend/:/app
    depends_on:
      - mariadb

  celery:
    build: ./backend/
    command: celery -A privbird worker -B -l INFO
    env_file:
        - .env.dev
    environment:
      DB_HOST: mariadb
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
        - backend
        - redis

  mariadb:
    hostname: mariadb
    image: mariadb
    restart: always
    env_file:
      - .env.dev

  redis:
    hostname: redis
    image: redis
  
  frontend:
    build: ./frontend
    volumes:
        - frontend_dist:/app/dist/
    env_file:
      - .env.dev

  nginx:
    build: ./nginx
    ports:
      - "8000:8000"
      - "80:80"
    volumes:
      - ./backend/:/backend/
      - frontend_dist:/frontend/
    depends_on:
      - backend
      - frontend
    links:
      - backend:backend

volumes:
  frontend_dist:
