version: '3'

services:
  backend:
    build: ./backend/
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    environment:
      DB_HOST: db
      CELERY_BROKER_URL: redis://redis:6379/0
    volumes:
      - ./backend/:/app/
    depends_on:
      - db

  celery:
    build: ./backend/
    command: celery -A privbird worker -B -l INFO
    depends_on:
        - backend
        - redis

  db:
    container_name: db
    hostname: db
    image: mariadb
    restart: always
    env_file:
      - .env.dev

  redis:
    hostname: redis
    image: redis:latest

  frontend:
    build: ./frontend/
    ports:
      - "8002:80"
    volumes:
      - .:/app
    links:
      - backend:backend
