version: '3'

services:
  backend:
    build: ./backend/
    command: gunicorn -c gunicorn.conf.py privbird.wsgi
    env_file:
      - .env.prod
    environment:
      DB_HOST: mariadb
      CELERY_BROKER_URL: redis://redis:6379/0
    volumes:
      - ./backend/:/app/
    depends_on:
      - mariadb

  celery:
    build: ./backend/
    command: celery -A privbird worker -B -l INFO
    environment:
      DB_HOST: mariadb
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
        - backend
        - redis

  nginx:
    build: ./nginx
    ports:
      - 8000:8000
      - 80:80
    volumes:
      - ./backend/:/backend/
      - ./frontend/:/frontend/
    depends_on:
      - backend
    links:
      - backend:backend

  mariadb:
    hostname: mariadb
    image: mariadb:latest
    restart: always
    env_file:
      - .env.prod
    volumes:
      - mysql_data:/var/lib/mysql/data/

  redis:
    hostname: redis
    image: redis:latest

volumes:
  mysql_data: