version: '3'

services:
    backend:
        build: ./backend/
        command: python ./backend/manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
        env_file:
            - .env.dev
        volumes:
            - .:/app
        depends_on:
            - db
    
    frontend:
        build: ./frontend/
        ports:
            - "8002:80"
        volumes:
            - .:/app
        links:
            - backend:backend
    
    db:
        image: mariadb
        restart: always
        env_file:
            - .env.dev
    
    redis:
        image: redis:6-alpine
