version: '3'

services:
  backend:
    build: ./backend/
    command: gunicorn -c gunicorn.conf.py privbird.wsgi
    env_file:
      - .env.prod
    environment:
      DB_HOST: mariadb
      REDIS_HOST: redis
    volumes:
      - ./backend/:/app/
    depends_on:
      - mariadb

  celery:
    build: ./backend/
    command: celery -A privbird worker -B -l INFO
    env_file:
        - .env.prod
    environment:
      DB_HOST: mariadb
      REDIS_HOST: redis
    depends_on:
        - backend
        - redis

  mariadb:
    hostname: mariadb
    image: mariadb
    restart: always
    env_file:
      - .env.prod
    volumes:
      - mysql_data:/var/lib/mysql/data/

  redis:
    hostname: redis
    image: redis
  
  frontend:
    build: ./frontend
    volumes:
        - frontend_dist:/app/dist/
    env_file:
      - .env.prod

  nginx:
    build: ./nginx
    ports:
      - "8000:8000"
      - "80:80"
    volumes:
      - ./backend/:/backend/
      - frontend_dist:/frontend/
    depends_on:
      - backend
      - frontend
    links:
      - backend:backend

volumes:
  mysql_data:
  frontend_dist:
