version: '3'

services:
  backend:
    build: ./backend/
    command: gunicorn -c ./backend/gunicorn.conf.py onetimelinks.wsgi
    expose:
      - "8000"
    env_file:
      - .env.prod
    volumes:
      - .:/app
    depends_on:
      - db

  celery:
    build: ./backend/
    command: celery -A onetimelinks worker -B -l INFO
    env_file:
      - .env.prod
    volumes:
      - .:/app
    depends_on:
      - backend

  frontend:
    build: ./frontend/
    ports:
      - "8002:80"
    volumes:
      - .:/app
    links:
      - backend:backend

  db:
    container_name: db
    hostname: db
    image: mariadb
    restart: always
    env_file:
      - .env.prod
    volumes:
      - mysql_data:/var/lib/mysql/data/

  redis:
    image: redis:6-alpine

volumes:
  mysql_data: