version: "3"

services:
  feedback:
    build: ./feedback/
    env_file:
      - .env.prod
    volumes:
      - ./feedback/:/app/
    depends_on:
      - mariadb
      - redis
    links:
      - redis:redis
      - mariadb:mariadb

  privnote:
    build: ./privnote/
    env_file:
      - .env.prod
    volumes:
      - ./privnote/:/app/
    depends_on:
      - mariadb
      - redis
    links:
      - redis:redis
      - mariadb:mariadb

  celery:
    build: ./privnote/
    command: celery -A privbird worker -B -l INFO
    env_file:
        - .env.prod
    depends_on:
        - privnote
    links:
      - redis:redis
      - mariadb:mariadb

  nginx:
    build: ./nginx/
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/log/:/var/log/nginx/
      - ./feedback/static/:/feedback/static/
      - ./privnote/static/:/privnote/static/
    depends_on:
      - feedback
      - privnote
    links:
      - feedback:feedback
      - privnote:privnote

  mariadb:
    image: mariadb
    restart: always
    env_file:
      - .env.dev
    volumes:
      - mysql_data:/var/lib/mysql/data/

  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/data/:/data/
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  mysql_data:
