version: "3"

services:
  privnote:
    build: ./
    command: gunicorn -c gunicorn.conf.py privnote.wsgi
    env_file:
      - .env
    volumes:
      - ./:/app/
    depends_on:
      - mariadb
      - redis
    links:
      - redis:redis
      - mariadb:mariadb

  celery:
    build: ./
    command: celery -A privnote worker -B -l INFO
    env_file:
      - .env
    depends_on:
      - privnote
      - rabbitmq
    links:
      - redis:redis
      - mariadb:mariadb

  nginx:
    build: ./nginx/
    ports:
      - "8001:8000"
    volumes:
      - ./nginx/log/:/var/log/nginx/
    depends_on:
      - privnote
    links:
      - privnote:privnote

  mariadb:
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql/data/

  redis:
    image: redis
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/data/:/data/
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

  rabbitmq:
    image: rabbitmq
    restart: always
    env_file:
      - .env
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"

volumes:
  mysql_data:
