version: "3.5"

services:
  feedback:
    build: ./
    command: gunicorn -c gunicorn.conf.py feedback.wsgi
    env_file:
      - .env
    volumes:
      - ./:/app/
    depends_on:
      - mariadb
      - redis
    links:
      - redis:redis
      - mariadb:mariadb
    networks:
      - internal

  nginx:
    build: ./nginx/
    volumes:
      - ./nginx/log/:/var/log/nginx/
      - ./feedback/static/:/feedback/static/
      - ./privnote/static/:/privnote/static/
    depends_on:
      - feedback
    links:
      - feedback:feedback
    networks:
      privbird:
        ipv4_address: 172.30.0.10
      internal:

  mariadb:
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql/data/
    networks:
      - internal

  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/data/:/data/
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - internal

volumes:
  mysql_data:

networks:
  internal:
  privbird:
    name: privbird
    driver: bridge
