version: "3.5"

services:
  feedback:
    build: ./
    command: gunicorn -c gunicorn.conf.py feedback.wsgi
    env_file:
      - .env
    volumes:
      - feedback_static:/app/static/
    depends_on:
      - mariadb
      - redis
    links:
      - redis:redis
      - mariadb:mariadb

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d
      - feedback_static:/feedback/static/
      - /var/log/backend/nginx/:/var/log/nginx/
    depends_on:
      - feedback
    links:
      - feedback:feedback
    ports:
      - "8000:8000"

  mariadb:
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql/data/

  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/data/:/data/
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  mysql_data:
  feedback_static:
