# Generated by Django 4.0 on 2022-11-03 05:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('password', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('notification', models.BooleanField(default=False)),
                ('fakeContent', models.TextField(blank=True, default=None, null=True)),
                ('fakePassword', models.TextField(blank=True, default=None, null=True)),
                ('fakeNotification', models.BooleanField(default=None, null=True)),
                ('salt', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('slug', models.SlugField(max_length=12, unique=True)),
                ('network', models.CharField(choices=[('HTTPS', 'Https'), ('TOR', 'Tor'), ('I2P', 'I2P')], default='HTTPS', max_length=5)),
                ('expires', models.DateTimeField(default=datetime.datetime(2023, 11, 3, 5, 13, 46, 671348, tzinfo=utc))),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
            ],
        ),
    ]
