# Generated by Django 4.1.3 on 2022-11-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="email",
            field=models.EmailField(default=None, max_length=256, null=True),
        ),
    ]
